services:
    bangpound_twitter_data.admin.hashtag:
        class: Bangpound\Twitter\DataBundle\Admin\HashtagAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Twitter, label: Hashtag }
        arguments:
            - ~
            - Bangpound\Twitter\DataBundle\Entity\Hashtag
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setParentAssociationMapping, [ 'tweets' ] ]

    bangpound_twitter_data.admin.media:
        class: Bangpound\Twitter\DataBundle\Admin\MediaAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Twitter, label: Media }
        arguments:
            - ~
            - Bangpound\Twitter\DataBundle\Entity\Media
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setParentAssociationMapping, [ 'tweets' ] ]

    bangpound_twitter_data.admin.place:
        class: Bangpound\Twitter\DataBundle\Admin\PlaceAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Twitter, label: Place }
        arguments:
            - ~
            - Bangpound\Twitter\DataBundle\Entity\Place
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setParentAssociationMapping, [ 'tweets' ] ]

    bangpound_twitter_data.admin.tweet:
        class: Bangpound\Twitter\DataBundle\Admin\TweetAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Twitter, label: Tweet }
        arguments:
            - ~
            - Bangpound\Twitter\DataBundle\Entity\Tweet
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ addChild, [ '@bangpound_twitter_data.admin.hashtag' ] ]
            - [ addChild, [ '@bangpound_twitter_data.admin.media' ] ]
            - [ addChild, [ '@bangpound_twitter_data.admin.url' ] ]
            - [ addChild, [ '@bangpound_twitter_data.admin.user_mention' ] ]
            - [ addChild, [ '@bangpound_twitter_data.admin.user' ] ]
            - [ addChild, [ '@bangpound_twitter_data.admin.place' ] ]

    bangpound_twitter_data.admin.url:
        class: Bangpound\Twitter\DataBundle\Admin\UrlAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Twitter, label: URL }
        arguments:
            - ~
            - Bangpound\Twitter\DataBundle\Entity\Url
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setParentAssociationMapping, [ 'tweets' ] ]

    bangpound_twitter_data.admin.user:
        class: Bangpound\Twitter\DataBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Twitter, label: User }
        arguments:
            - ~
            - Bangpound\Twitter\DataBundle\Entity\User
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setParentAssociationMapping, [ 'tweets' ] ]

    bangpound_twitter_data.admin.user_mention:
        class: Bangpound\Twitter\DataBundle\Admin\UserMentionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Twitter, label: User Mention }
        arguments:
            - ~
            - Bangpound\Twitter\DataBundle\Entity\UserMention
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setParentAssociationMapping, [ 'tweets' ] ]
