services:
    bangpound_twitter_data.admin.tweet:
        class: Bangpound\Twitter\DataBundle\Admin\TweetAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Twitter, label: Tweet }
        arguments:
            - ~
            - Bangpound\Twitter\DataBundle\Entity\Tweet
            - 'SonataAdminBundle:CRUD'
