parameters:
#    bangpound_twitter_data.example.class: Bangpound\Twitter\DataBundle\Example

services:
#    bangpound_twitter_data.example:
#        class: %bangpound_twitter_data.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
